version: 2.1
parameters:
  CI_EVENT_TYPE:
    type: string
    default: "push"
  CI_REPOSITORY_URL:
    type: string
    default: ""

jobs:
  build:
    environment:
      CI_EVENT_TYPE: "<< pipeline.parameters.CI_EVENT_TYPE >>"
      CI_REPOSITORY_URL: "<< pipeline.parameters.CI_REPOSITORY_URL >>"
      HTTPD_IMAGE_NAME: rimelek/httpd24
      HTTPD_IMAGE_NAME_ALTERNATIVE: "itsziget/httpd24"
    resource_class: medium
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run:
          name: Docker login
          command: ./ci/local-builder.sh bash -c "echo \"$DOCKER_HUB_PASS\" | docker login -u \"$DOCKER_HUB_USER\" --password-stdin"
      - run:
          name: Build Docker image
          command: ./.circleci/step-build-docker-image.sh
      - run:
          name: List docker images
          command: docker image ls

      - run:
          name: Deploy Docker image
          command: ./.circleci/step-deploy-docker-image.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /^\d+\.\d+(-dev)?$/
                - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
