version: 2.1
parameters:
  CI_EVENT_TYPE:
    type: string
    default: "push"

jobs:
  build:
    environment:
      CI_EVENT_TYPE: "<< pipeline.parameters.CI_EVENT_TYPE >>"
    resource_class: medium
    machine:
      image: ubuntu-2004:202111-02
#     resource_class: small
#     docker:
#       image: cimg/python:3.8
    steps:
      - checkout
#       - setup_remote_docker:
#           # CircleCI still does not support 20.10.12
#           version: 20.10.11
#           # The free plan does not support caching0
#           docker_layer_caching: false
      - run:
          name: Docker login
          command: echo "${DOCKER_HUB_PASS}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin
#       - run:
#           name: Install python requirements
#           command: pip install -r ci/requirements.txt
#       - run:
#           name: Debug python packages
#           command: pip freeze | sort
      - run:
          name: Make build.sh executable
          command: chmod +x ./ci/build.sh
      - run:
          name: Docker info
          command: docker info
      - run:
          name: Build Docker image
          command: |

            # the empty line above is for pycharm syntax highlighting...
            ./ci/local-builder.sh ./ci/build.sh -i "${HTTPD_IMAGE_NAME}" -t "${CIRCLE_TAG}" -b "${CIRCLE_BRANCH}" -T "${HTTPD_WAIT_TIMEOUT}" -e "${CI_EVENT_TYPE}" -B "circleci-${CIRCLE_BUILD_NUM}"
      - run:
          name: List docker images
          command: docker image ls

      - run:
          name: Make build.sh executable
          command: chmod +x ./ci/deploy.sh
      - run:
          name: Deploy Docker image
          command: |

            # the empty line above is for pycharm syntax highlighting...
            ./ci/deploy.sh -i "${HTTPD_IMAGE_NAME}" -t "${CIRCLE_TAG}" -b "${CIRCLE_BRANCH}" -e "${CI_EVENT_TYPE}" -B "circleci-${CIRCLE_BUILD_NUM}"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /^\d+\.\d+(-dev)?$/
                - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
